Instance: d69b9107-ca0a-461a-b3d7-6d15995389b3
InstanceOf: Bundle
Usage: #example
* meta.lastUpdated = "2022-12-14T19:56:25.247-03:00"
* type = #collection
* entry[0].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRCategoriaExame-1.0"
* entry[=].resource = BRCategoriaExame-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BREstadoDocumento-1.0"
* entry[=].resource = BREstadoDocumento-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BREstadoObservacao-1.0"
* entry[=].resource = BREstadoObservacao-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BREtniaIndigena-1.0"
* entry[=].resource = BREtniaIndigena-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRMunicipio-1.0"
* entry[=].resource = BRMunicipio-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRNacionalidade"
* entry[=].resource = Inline-Instance-for-d69b9107-ca0a-461a-b3d7-6d15995389b3-1
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRNaturezaJuridica-1.0"
* entry[=].resource = BRNaturezaJuridica-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRNomeExame-1.0"
* entry[=].resource = BRNomeExame-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRNomeExame-2.0"
* entry[=].resource = BRNomeExame-2.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BROcupacao-1.0"
* entry[=].resource = BROcupacao-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BROrgaoExpedidor-1.0"
* entry[=].resource = BROrgaoExpedidor-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRPais-1.0"
* entry[=].resource = BRPais-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRParentesco-1.0"
* entry[=].resource = BRParentesco-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRRacaCor-1.0"
* entry[=].resource = BRRacaCor-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRResultadoQualitativoExame-1.0"
* entry[=].resource = BRResultadoQualitativoExame-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRResultadoQualitativoExame-2.0"
* entry[=].resource = BRResultadoQualitativoExame-2.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRSexo-1.0"
* entry[=].resource = Inline-Instance-for-d69b9107-ca0a-461a-b3d7-6d15995389b3-2
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRTerminologiaPatogeno"
* entry[=].resource = BRTerminologiaPatogeno
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRTerminologiaSuspeitaDiagnostica"
* entry[=].resource = BRTerminologiaSuspeitaDiagnostica
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRTipoAmostra-1.0"
* entry[=].resource = BRTipoAmostra-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRTipoDocumento-1.0"
* entry[=].resource = BRTipoDocumento-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRTipoDocumentoIndividuo-1.0"
* entry[=].resource = BRTipoDocumentoIndividuo-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRTipoEstabelecimentoSaude-1.0"
* entry[=].resource = BRTipoEstabelecimentoSaude-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRTipoLogradouro-1.0"
* entry[=].resource = BRTipoLogradouro-1.0
* entry[+].fullUrl = "https://rnds-fhir.saude.gov.br/ValueSet/BRUnidadeFederativa-1.0"
* entry[=].resource = BRUnidadeFederativa-1.0